### ISSUE TITLE
some questions with mode 3?

### ISSUE THREAD

**Issue by omlomloml** [futurewei-cloud/caerus-semantic-cache#1]
if I run q007 using spark-shell, the first time the manager will create a cached content  and spark will use the content, so far so good
in the same spark session, if I re-run the query, but the second time, instead of using the existing cache content, the manager will a second cache(identical to me) and use that.

is this a bug or do I used it wrong?

**Comment by tedgoud** [comment]
No this is a bug. Can you send me the client and the manager log (tedgoud@gmail.com)?
